<?php

namespace Querdos\ChallengeMe\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    /**
     * Return the count of all existing teams
     *
     * @return int
     */
    public function count()
    {
        $query = $this
            ->getEntityManager()
            ->createQueryBuilder()

            ->select('COUNT(team)')
            ->from('UserBundle:Team', 'team')
        ;

        return $query
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
