<?php

namespace Querdos\ChallengeMe\AdministratorBundle\Repository;

/**
 * AdminstratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminstratorRepository extends \Doctrine\ORM\EntityRepository
{
}
