<?php

namespace Querdos\ChallengeMe\AdministratorBundle\Repository;

/**
 * InfoUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoUserRepository extends \Doctrine\ORM\EntityRepository
{
}
