<?php

namespace Querdos\ChallengeMe\AdministratorBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Querdos\ChallengeMe\AdministratorBundle\Entity\Moderator;

/**
 * ModeratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeratorRepository extends EntityRepository
{
    public function create(Moderator $moderator) {
        $this->getEntityManager()->persist($moderator);
        $this->getEntityManager()->flush();
    }

    public function update(Moderator $moderator) {
        $this->getEntityManager()->persist($moderator);
        $this->getEntityManager()->flush();
    }

    public function delete(Moderator $moderator) {
        $this->getEntityManager()->remove($moderator);
        $this->getEntityManager()->flush();
    }
}
